### ISSUE TITLE
-Wformat-overflow complaint on sprintf call

### ISSUE THREAD

**Issue by fadden** [apple2accumulator/merlin32#12]
Seeing this with gcc v7.4.0 on Ubuntu 18.04.2:

    gcc -Icompat -DUNIX   -c -o a65816_Link.o a65816_Link.c
    a65816_Link.c: In function 'AssembleLink65c816':
    a65816_Link.c:66:30: warning: 'error_output.txt' directive writing 16 bytes into a region of size between 1 and 1024 [-Wformat-overflow=]
       sprintf(file_error_path,"%serror_output.txt",param->current_folder_path);
                                  ^~~~~~~~~~~~~~~~
    a65816_Link.c:66:3: note: 'sprintf' output between 17 and 1040 bytes into a destination of size 1024
       sprintf(file_error_path,"%serror_output.txt",param->current_folder_path);

Can be fixed by increasing the size of `file_error_path` so it can hold the 1024 bytes from `param->current_folder_path` plus `strlen("error_output.txt")`.  And preferably switching to `snprintf()`.

**Comment by lroathe** [comment]
This can be closed as soon as the pull request for this issue is merged.
