### ISSUE TITLE
L@@K! STEVE JOBS! merlin32 needs a proper symbol table. 

### ISSUE THREAD

**Issue by berighteous** [apple2accumulator/merlin32#28]
Merlin32 desperately needs a symbol table both in numerical and alphabetical order.  Merlin did it on the apple ][ 40 years ago.  Merlin32 needs this essential feature.  URGENT TOP PRIORITY NOTHING ELSE MATTERS UNTIL THIS IS ADDED!!!  L@@K!  STEVE JOBS!

**Comment by berighteous** [comment]
![symbol table](https://user-images.githubusercontent.com/56898881/67343459-90cb0d00-f4f2-11e9-980f-074e132508c8.jpg)

**Comment by berighteous** [comment]
I write apple ][ games - Alien Downpour, OidZone, Darkstar Unhinged, and more.  I typically have hundreds of symbols, variables, fiddly numbers I need to keep track of, that may move around in memory as I work on it.  I need a proper symbol table generated every assembly so I can check to see if the code is putting the correct thing in the correct place.

**Comment by lroathe** [comment]
Do you want the symbol table output to the "_output.txt" file, or to the console, or ???

Also, would it be OK if the program labels were separate from the equate values, or must they be combined?

**Comment by lroathe** [comment]
This can be closed with the related pull request is merged.

**Comment by gungwald** [comment]
Fixed by https://github.com/lroathe/merlin32/commit/1f988dcefe5ee05204a911c132ecabb0592ee9ae
