### ISSUE TITLE
Reduce sensitivity to end-of-line characters

### ISSUE THREAD

**Issue by fadden** [apple2accumulator/merlin32#3]
On Linux, a source file with CRLF will fail strangely, because the ^M gets treated as part of the line.

This is particularly confusing because the '^M' gets printed in the error message, moving the output cursor back to the start of the line.

**Comment by gungwald** [comment]
This is actually correct behavior for Linux/Unix where the ^J is an end-of-line and everything else is data. But I agree that it is such a problem that it would be good for merlin to handle it more gracefully. The normal way to compensate for this is to have tool that transfers the file to Linux do the conversion. Git and ftp (in ASCII mode) should do this. However, scp and sftp do not. So you have to run dos2unix on the file if your transfer tool does not do the conversion for you. I'll look into how this could be done.

**Comment by gungwald** [comment]
Lane already fixed this.
