### ISSUE TITLE
DSK is allowed in link files and assembly files

### ISSUE THREAD

**Issue by ksherlock** [apple2accumulator/merlin32#35]
https://github.com/apple2accumulator/merlin32/blob/285f00e76f0df921eaa51989050280fc090afb29/Source/a65816_Link.c#L655

^^^
causes assembly files with a DSK opcode to (incorrectly) be treated as a link file, with predictable results.

**Comment by digarok** [comment]
Assuming the following code in a file called `test.s`:
```
 org $2000
 dsk myapp
 sta $ff
```

Previously (Brutal Deluxe) builds of Merlin would assemble that fine and create a 2-byte file called "myapp".

Now I'm getting the following error as though it's trying to treat it as a link file:
```
$ ~/appleiigs/tools/merlin32 test.s
/Users/dbrock/appleiigs/tools/merlin32 v1.1.8, (c) Brutal Deluxe 2011-2015
  + Loading Link file...
     => Error, Invalid Link file : Unknown (or misordered) directive found (org) at line 1.
      => [Error] Impossible to load Link file 'test.s'. 
```

**Comment by digarok** [comment]
Also, `TYP` is valid for assembly file as well.

**Comment by fadden** [comment]
I'm seeing the same thing -- simple programs with ORG statements will not assemble.

**Comment by gungwald** [comment]
This bug was fixed by this commit https://github.com/lroathe/merlin32/pull/2/commits/307813e0ba49003cbd48f8ab3c52338f3e41ef16
