### ISSUE TITLE
Doesn't generate valid OMF

### ISSUE THREAD

**Issue by dwsJason** [apple2accumulator/merlin32#40]
Why I try to build any of my GSOS projects using this version of Merlin, I get an error when trying to launch the application.
system error $004D

with Merlin v1.0 from the BD website, valid OMF is generated.

**Comment by dwsJason** [comment]
I tried removing the xpl, ExpressLoad segment from my linker file, when I do this I instead get a system error $1102 when I try to launch the generated executable.

**Comment by fadden** [comment]
The code on [lroathe's branch](https://github.com/lroathe/merlin32) is newer.  Try that first.

If you want to dig at it, BD has a command-line [OMF dump utility](https://www.brutaldeluxe.fr/products/crossdevtools/omfanalyzer/index.html), and I added a GUI tool to [SourceGen](https://github.com/fadden/6502bench).  Comparing old vs. new output might be enlightening.

**Comment by dwsJason** [comment]
I'll try Lane's,  OMFAnalyzer won't even dump it or diff it against the good executable.

**Comment by dwsJason** [comment]
Please get lroathes changes, as they fix this issue with system complaining when trying to launch a GSOS executable built with merlin.
